[package]
name = "kara-ui"
description = "Puente cxx-qt y binario principal de Kara."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cxx = "1.0.199"
cxx-qt = "0.10.0"
cxx-qt-lib = { version = "0.10.0", features = ["qt_gui", "qt_qml", "qt_quickcontrols"] }
kara-core.workspace = true
kara-fs.workspace = true
kara-index.workspace = true
kara-ops.workspace = true

[build-dependencies]
cxx-qt-build = "0.10.0"
